conn / as sysdba

SET MARKUP HTML ON TABLE "class=tabela_status" ENTMAP OFF

spool /home/oracle/bin/report_bkp/status.txt APPEND

set termout off feedback off verify off heading on echo off

COLUMN TABLESPACE_NAME FORMAT A20;
SELECT A.TABLESPACE_NAME NOME,
       NVL(ROUND(((C.BYTES - NVL(B.BYTES, 0)) / C.BYTES) * 100, 2), 0)  "USO EM %",
       ROUND(C.BYTES / 1024 / 1024 - NVL(B.BYTES, 0) / 1024 / 1024, 2)  "USO EM MB"
FROM DBA_TABLESPACES A,
       (SELECT TABLESPACE_NAME, SUM(BYTES) BYTES
          FROM DBA_FREE_SPACE
         GROUP BY TABLESPACE_NAME) B,
       (SELECT COUNT(1) DATAFILES, SUM(BYTES) BYTES, TABLESPACE_NAME
          FROM DBA_DATA_FILES
         GROUP BY TABLESPACE_NAME) C
WHERE B.TABLESPACE_NAME(+) = A.TABLESPACE_NAME
   AND C.TABLESPACE_NAME(+) = A.TABLESPACE_NAME
ORDER BY NVL(((C.BYTES - NVL(B.BYTES, 0)) / C.BYTES), 0) DESC;
--ORDER BY NVL(ROUND(((C.BYTES - NVL(B.BYTES, 0)) / C.BYTES) * 100, 2), 0) DESC;

spool off
exit
