/*
ANDRÉ DEL CAMPO SPADINI                                       
EMAIL: andrespadini@yahoo.com.br                              
TEL: 16-99186-4264                                            
*/ 

SET PAGESIZE 999
SET LINESIZE 132
SET SERVEROUTPUT ON SIZE UNLIMITED FORMAT WRAPPED
DEFINE _EDITOR = /usr/bin/vim
COLUMN segment_name FORMAT A30 WORD_WRAP
COLUMN object_name FORMAT A30 WORD_WRAP
SET SQLPROMPT "_USER'@'_CONNECT_IDENTIFIER > "


COL DISK_GROUP_NAME FORMAT A30
COL DISK_FILE_PATH FORMAT A30
COL DISK_FILE_NAME FORMAT A30 
COL DISK_FILE_FAIL_GROUP FORMAT A30
